development:
  host: localhost
  database: steerpike_development
  sessions:
    default:
      database: mongoid
      hosts:
        - localhost:27017

test:
  host: localhost
  database: steerpike_test
  sessions:
    default:
      database: mongoid
      hosts:
        - localhost:27017

# set these environment variables on your prod server
production:
  host: <%= ENV['MONGOID_HOST'] %>
  port: <%= ENV['MONGOID_PORT'] %>
  username: <%= ENV['MONGOID_USERNAME'] %>
  password: <%= ENV['MONGOID_PASSWORD'] %>
  database: <%= ENV['MONGOID_DATABASE'] %>
  # slaves:
  #   - host: slave1.local
  #     port: 27018
  #   - host: slave2.local
  #     port: 27019
